config/routes.rb
Rails.application.routes.draw do
  
  get    '/ajuda',   to: 'help#help'
  get    '/geral',   to: 'general#general'
  get    '/signup',  to: 'users#new'
  get    '/goods/buscando', to: 'goods#searching'
  get    '/sales/buscando', to: 'sales#searching'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, exception: [:new, :create]
  resources :goods
  resources :expenses
  resources :sales

  post  'sales/busca' => 'sales#search' 
  post  'goods/busca' => 'goods#search' 
  post 'geral/busca' => 'general#search'

  resources :users do
  	get :current, on: :collection # users#current
  end

  root 'users#current_user_menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  
  validates :name, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true

  has_many :goods, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :sales, dependent: :destroy
  
  has_secure_password

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:current_user_menu, :show, :index, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users/1
  # GET /users/1.json
  def show
  end

  def index
    redirect_to current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Bem-vindo ao Simple Merch!"
      log_in @user
      redirect_to @user
    else
      flash[:danger] = "Ops.. Algo não está correto!"
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to current_user
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
  end

  def current_user_menu
    redirect_to current_user
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def logged_in_user
      unless logged_in?
        flash[:success]= "Por favor, faça seu Log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h3 align="center">Editando informações do usuário</h3>

<div class="formDiv row">
  <%= form_for @user, html: { autocomplete: "off" } do |f| %>
    <div style="text-align: left;">
      <%= f.label :name, "Nome:" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password,"Senha:" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme sua senha:" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
      <br>
      <%= f.submit "Editar minha conta", class: "btn btn-primary" %>
  <% end %>
    <br>
    <%= link_to "Voltar", root_path%></p>
</div>

app/views/users/history.html.erb
(em ordem de cadastro)
<h1>Histórico de vendas:</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Preço(u)</th>
      <th>Lucro</th>
      <th>Vendido à</th>
      <th>Dia</th>
      <th>Mês</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.good.description %></td>
        <td><%= sale.quantity %></td>
        <td><%= number_to_currency(sale.sell_price,  :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
        <td><%= number_to_currency(sale.quantity*(sale.sell_price - sale.good.buy_price),  :unit => "R$ ", :separator => ",", :delimiter => ".") %>
        <td><%= sale.sold_to %></td>
        <td><%= sale.sell_day %></td>
        <td><%= sale.sell_month %></td>
        <td><%= sale.sell_year %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h1>Histórico de mercadorias:</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Preço(u)</th>
      <th>Comprado de</th>
      <th>Tipo</th>
      <th>Dia</th>
      <th>Mês</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.description %></td>
        <td><%= number_to_currency(good.buy_price,  :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
        <td><%= good.buyed_from %></td>
        <td><%= good.kind %></td>
        <td><%= good.buy_day %></td>
        <td><%= good.buy_month %></td>
        <td><%= good.buy_year %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<h1>Histórico de despesas:</h1>

<table>
  <thead>
    <tr>
      <th>Custo</th>
      <th>Tipo</th>
      <th>Motivo</th>
      <th>Dia</th>
      <th>Mês</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= number_to_currency(expense.cost,  :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
        <td><%= expense.kind %></td>
        <td><%= expense.reason %></td>
        <td><%= expense.day %></td>
        <td><%= expense.month %></td>
        <td><%= expense.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 align="center">Cadastro</h1>

<div class="formDiv row">
  <%= form_for @user, html: { autocomplete: "off" } do |f| %>
    <div style="text-align: left;">
      <%= f.label :name, "Seu nome:" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "E-mail:" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password,"Senha:" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirme sua senha:" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <br>
    <%= f.submit "Criar minha conta", class: "btn btn-primary" %>
  <% end %>
  <p>Já possui conta? <%= link_to "Logue-se!", login_path%></p>
</div>

app/views/users/show.html.erb
<div>
	<div class="menuDiv">
		<div align="center" >
			<%= link_to geral_path do %>
				<div class="menuButton">
					<div class="inlineblockDiv" style="margin: 20px;">
						<%= image_tag "Tabela_pixel.png" %>
						<section style="color: white;">
							<b>Geral</b>
						</section>
					</div>
				</div>
			<% end %>
			<%= link_to goods_path do %>
				<div class="menuButton " >
					<div class="inlineblockDiv" style="margin: 20px;">
						<%= image_tag "Caixa_pixel.png" %>
						<section style="color: white;">
							<b>Estoque</b>
						</section>
					</div>
				</div>
			<% end %>
		</div>

		<div align="center">
			<%= link_to sales_path do %>
				<div class="menuButton">
					<div class="inlineblockDiv" style="margin: 20px;">
						<%= image_tag "Sifrao-mais_pixel.png" %>
						<section style="color: white;">
							<b>Venda</b>
						</section>
					</div>
				</div>
			<% end %>
			<%= link_to new_expense_path do %>
				<div class="menuButton">
					<div class="inlineblockDiv" style="margin: 20px;">
						<%= image_tag "Sifrao-menos_pixel.png" %>
						<section style="color: white;">
							<b>Despesa</b>
						</section>
					</div>
				</div>
			<% end %>
		</div>	

		<div align="center">
			<%= link_to new_good_path do %>
				<div class="menuButton">
					<div class="inlineblockDiv" >
						<%= image_tag "Caminhao_pixel.png" %>
						<section style="color: white;">
							<b>Entrada de Mercadoria</b>
						</section>
					</div>
				</div>	
			<% end %>
			<%= link_to ajuda_path do %>
				<div class="menuButton">
					<div class="inlineblockDiv" style="margin: 20px;">
						<%= image_tag "Interrogação_pixel.png" %>
						<section style="color: white;">
							<b>Ajuda</b>
						</section>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>