config/routes.rb
Rails.application.routes.draw do
  
  get    '/ajuda',   to: 'help#help'
  get    '/geral',   to: 'general#general'
  get    '/signup',  to: 'users#new'
  get    '/goods/buscando', to: 'goods#searching'
  get    '/sales/buscando', to: 'sales#searching'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, exception: [:new, :create]
  resources :goods
  resources :expenses
  resources :sales

  post  'sales/busca' => 'sales#search' 
  post  'goods/busca' => 'goods#search' 
  post 'geral/busca' => 'general#search'

  resources :users do
  	get :current, on: :collection # users#current
  end

  root 'users#current_user_menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/good.rb
class Good < ApplicationRecord
	before_validation :comma_to_dot

	belongs_to :user
	has_many :sales, dependent: :destroy

	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :description, presence: true, uniqueness: { case_sensitive: false}, uniqueness: false
	validates :quantity, presence: true
	validates :buy_price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	validates :buy_day, presence: true, :inclusion => { :in => 1..31, :message => "Digite o dia entre 1-31" }
	validates :buy_month, presence: true, :inclusion => { :in => 1..12, :message => "Digite o mês entre 1-12" }
	validates :buy_year, allow_nil: true, :inclusion => {:in => 1919..2019, :message => "Esse ano não é valido"}

	validates :note, length: { maximum: 255 }

	def comma_to_dot
    	self.buy_price = self.buy_price.to_s.gsub(/,/,'.').to_f
    end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :new, :edit, :update, :destroy]  

  def searching
  end

  def search
    @goods = current_user.goods.where("quantity > ?", 0)
    @goods = @goods.where("description LIKE ?", "%#{params[:description]}%") if params[:description] != ""
    @goods = @goods.where("buy_day = ?", params[:buy_day]) if params[:buy_day] != ""
    @goods = @goods.where("buy_month = ?", params[:buy_month]) if params[:buy_month] != ""
    @goods = @goods.where("buy_year = ?", params[:buy_year]) if params[:buy_year] != ""
    @goods = @goods.where("kind LIKE ?", "%#{params[:kind]}%") if params[:kind] != ""
    @goods = @goods.where("buyed_from LIKE ?", "%#{params[:buyed_from]}%") if params[:buyed_from] != ""
    
    @stock_value = 0
    @stock_quantity = 0
    
    render template: 'goods/index' 
  end

  # GET /goods
  # GET /goods.json
  def index
    @goods = current_user.goods.where("quantity > ?", 0)
    @stock_value = 0
    @stock_quantity = 0
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
    if good.quantity < 1
      redirect_to root_url
    end
  end

  # POST /goods
  # POST /goods.json
  def create
    if good_params[:buy_year] == "" || good_params[:buy_year].nil?
      good_params[:buy_year] = 2018
    end
    
    @good = current_user.goods.build(good_params)
    if @good.save
      flash[:success] = "Mercadoria criada!"
      redirect_to goods_url
    else
      flash[:danger] = "Ops.. Algo não está correto!"
      render 'new'
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    if @good.update(good_params)
      flash[:success] = "Mercadoria atualizada!"
    else
      
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:description, :quantity, :user_id, :buy_price, :buyed_from, :buy_day, :buy_month, :buy_year, :kind, :note)
    end

    def logged_in_user
      unless logged_in?
        flash[:success]= "Por favor, faça seu Log in"
        redirect_to login_url
      end
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_good.html.erb
	<div class="divStock"style="border: 1px solid #d9d9d9; max-width: 500px; min-width: 294px; height: 85px;margin-top: 1px;" >
	<%= link_to good do %>
		<div style="max-width: 400px; border: 1px solid transparent; height: 85px;">
			<div class="inlineblockDiv"style="width: 60px; height: 60px; float: left; border: 1px solid #d9d9d9; margin: 10px">
			</div>
			<b style="font-size: 1em"><%= good.description %></b>
			<% @stock_value = @stock_value + (good.buy_price*good.quantity) %>
			<% @stock_quantity = @stock_quantity + good.quantity %>
			<br>
			<div class="inlineblockDiv" style="text-align: left;">
				<span style="font-size: 0.75em; margin-right: 12px;">Preço(und): <%= number_to_currency(good.buy_price,  :unit => "R$ ", :separator => ",", :delimiter => ".") %></span>
				<% if good.kind == "" %>
					<span style="font-size: 0.75em;">Tipo: -</span>
				<% else %>
					<span style="font-size: 0.75em;">Tipo: <%=good.kind %></span>
				<% end %>
				<br>
				<span style="font-size: 0.75em; margin-right: 12px;">Quantidade: <%= good.quantity %></span>
				<span style="font-size: 0.75em;">Data: <%= good.buy_day %>/<%= good.buy_month %>/<%= good.buy_year %></span>
				<br>
				<% if good.buyed_from == "" %>
					<span style="font-size: 0.75em; margin-right: 12px;">Origem: -</span>
				<% else %>
					<span style="font-size: 0.75em; margin-right: 12px;">Origem: <%=good.buyed_from %></span>
				<% end %>
			</div>
		</div>
<% end %>

	</div>

app/views/goods/index.html.erb
<div style="min-height:100%; padding-bottom: 40px; margin-bottom: -40px;">
<% if @goods.any? %>
	<div class="estoque">
		 <span style="font-size: 1.3em;">Mercadorias em estoque:</span>
		 <span style="float: right;"><%= link_to "Busca", goods_buscando_path %></span>	
	</div>
	<div  align="center" style="padding-bottom: 50px; width: 100%; min-width: 320px; margin-bottom: 40px">
		<%= render @goods %>
		<%= link_to "Nova entrada de mercadoria?", new_good_path %>
	</div>
<% else %>
	<section align="center">
		<article style="text-align: center; margin: 10px; margin-top: 60px;">
			<h3>Nenhuma mercadoria em estoque... <br><%= link_to "Cadastrar entrada de uma mercadoria?", new_good_path %></h3>
		</article>
	</section>
<% end %>
</div>

<div align="center" class="navbar navbar-fixed-bottom footer">
	<div class="inlineblockDiv">
		<div style="text-align: left;">
			<span style="font-size: 1.3em; color: white;">Total</span>
		</div>
		<div>
		<div class="inlineblockDiv" style="text-align: left;">
			<b style="font-size: 1.1em;">Valor em estoque:</b>
			<br>
			<b style="font-size: 1.1em;">Quantidade em estoque:</b>
		</div>
		<div class="inlineblockDiv" style="text-align: right;">
			<span style="color: green; font-size: 1.2em;"><%= number_to_currency(@stock_value,  :unit => "R$ ", :separator => ",", :delimiter => ".") %></span><br>
			<span style="font-size: 1.2em;"><%= @stock_quantity %></span>
		</div>
		</div>
	</div>
</div>


app/views/goods/new.html.erb
<h3 align="center">Entrada de Mercadoria</h3>

<div class="formDiv row">
  <%= form_for @good, html: { autocomplete: "off" } do |f| %>
    <div style="text-align: left;">
      <%= f.label :description, "Descrição ou Nome:" %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :quantity, "Quantidade:" %>
      <%= f.number_field :quantity, class: 'form-control' %>

      <%= f.label :buy_price, "Preço de compra por unidade: (R$)" %>
      <%= f.text_field :buy_price, step: 0.01, :placeholder => 'ex.: 123,45', class: 'form-control' %>

      <div style="width: auto;">
        <div class="inlineblockDiv">
          <%= f.label :buy_day , "Dia:" %>
          <%= f.text_field :buy_day, class: 'form-control', style: "width: 45px;" %>
        </div>

        <div class="inlineblockDiv">
          <%= f.label :buy_month, "Mês:" %>
          <%= f.text_field :buy_month, class: 'form-control', style: "width: 45px;" %>
        </div>

        <div class="inlineblockDiv">
          <%= f.label :buy_year, "Ano:" %>
          <%= f.text_field :buy_year, :placeholder => '2018..', class: 'form-control', style: "width: 60px;" %>
        </div>
      </div>
      
      <%= f.label :kind, "Tipo de mercadoria: (Opcional)" %>
      <%= f.text_field :kind, :placeholder => 'ex.: Bijuteria, Quadro, Cosmético..', class: 'form-control' %>

      <%= f.label :buyed_from, "Fornecedor da mercadoria: (Opcional)" %>
      <%= f.text_field :buyed_from, :placeholder => 'ex.: Vendedor, Loja, Leilão..', class: 'form-control' %>
    </div>
    <br>
    <%= f.submit "Cadastrar mercadoria", class: "btn btn-primary" %>
  <% end %>
</div>
<br>
<%= link_to "Voltar", :back %>

app/views/goods/searching.html.erb
<h5 align="center" style="color: gray;">Preencha apenas as informações que deseje filtrar </h5> 

<h2 align="center">Busca no estoque</h2>
<div class="formDiv row">
	<%= form_tag "/goods/busca", autocomplete: 'off' do %>
		<div style="text-align: left;">
			<%= label :description, "Descrição ou Nome:" %>
			<%= text_field_tag :description, params[:description], class: 'form-control' %>

			<div style="width: auto;">
				<div class="inlineblockDiv" style="margin-left: auto;">
					<%= label :buy_day, "Dia:" %>
					<%= text_field_tag :buy_day, params[:buy_day], class: 'form-control', style: "width: 45px;" %>
				</div>
				<div class="inlineblockDiv" style="margin: auto;">
					<%= label :buy_month, "Mês:" %>
					<%= text_field_tag :buy_month, params[:buy_month], class: 'form-control', style: "width: 45px;" %>
				</div>
				<div class="inlineblockDiv" style="margin: auto;">
					<%= label :buy_year, "Ano:" %>
					<%= text_field_tag :buy_year, params[:buy_year], :placeholder => '2018', class: 'form-control', style: "width: 60px;" %>
				</div>
			</div>
			
			<%= label :buyed_from, "Fornecedor da mercadoria:" %>
			<%= text_field_tag :buyed_from, params[:buyed_from], :placeholder => 'ex.: Vendedor, Loja, Leilão..', class: 'form-control' %>

			<%= label :kind, "Tipo de mercadoria:" %>
			<%= text_field_tag :kind, params[:kind], :placeholder => 'ex.: Cristal, Quadro, Cosmético..', class: 'form-control' %>
		</div>
		<br>
		<%= submit_tag "Buscar", class: "btn btn-primary buttons" %>
	<% end %>
</div>
<br>
<%= link_to "Voltar", :back %>