config/routes.rb
Rails.application.routes.draw do
  
  get    '/ajuda',   to: 'help#help'
  get    '/geral',   to: 'general#general'
  get    '/signup',  to: 'users#new'
  get    '/goods/buscando', to: 'goods#searching'
  get    '/sales/buscando', to: 'sales#searching'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, exception: [:new, :create]
  resources :goods
  resources :expenses
  resources :sales

  post  'sales/busca' => 'sales#search' 
  post  'goods/busca' => 'goods#search' 
  post 'geral/busca' => 'general#search'

  resources :users do
  	get :current, on: :collection # users#current
  end

  root 'users#current_user_menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :user
	belongs_to :good

	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: :true
	validates :good_id, presence: :true
	validates :quantity, presence: true
	validates :sell_price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	validates :sell_day, presence: true, :inclusion => { :in => 1..31, :message => "Digite o dia entre 1-31" }
	validates :sell_month, presence: true, :inclusion => { :in => 1..12, :message => "Digite o mês entre 1-12" }
	validates :sell_year, allow_nil: true, :inclusion => {:in => 2017..2019, :message => "Esse ano não é valido"}
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  
  def searching
  end

  def search
    @goods = current_user.goods.where("quantity > ?", 0)
    @goods = @goods.where("description LIKE ?", "%#{params[:description]}%") if params[:description] != ""
    @goods = @goods.where("buy_day = ?", params[:buy_day]) if params[:buy_day] != ""
    @goods = @goods.where("buy_month = ?", params[:buy_month]) if params[:buy_month] != ""
    @goods = @goods.where("buy_year = ?", params[:buy_year]) if params[:buy_year] != ""
    @goods = @goods.where("kind LIKE ?", "%#{params[:kind]}%") if params[:kind] != ""
    @goods = @goods.where("buyed_from LIKE ?", "%#{params[:buyed_from]}%") if params[:buyed_from] != ""
    
    render template: 'sales/index' 
  end

  # GET /sales
  # GET /sales.json
  def index
    @goods = current_user.goods.where("quantity > ?", 0)    
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @good = Good.find(params[:param])
    redirect_to(goods_url) unless current_user.id == @good.user_id || current_user.admin? || @good.quantity == 0
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    if sale_params[:sell_year] == "" || sale_params[:sell_year].nil?
      sale_params[:sell_year] = 2018
    end

    @sale = current_user.sales.build(sale_params)
    @good = Good.find(sale_params[:good_id])
    if sale_params[:sell_year] == ""
      sale_params[:sell_year] = 2018
    end
    if @sale.quantity > @good.quantity
      flash[:danger] = "Não venda além do que possui.."
      redirect_to goods_url
    else
      if @sale.save
        quantity = @good.quantity - @sale.quantity
        if @good.update(:quantity => quantity)
          flash[:success] = "Venda realizada!"
          redirect_to sales_url          
        end
      else
        redirect_to sales_url
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    if @sale.update(sale_params)
      redirect_to current_user
    else
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    if @sale.destroy
      redirect_to current_user
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:user_id, :good_id, :quantity, :sell_price, :sold_to, :sell_day, :sell_month, :sell_year)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/index.html.erb
<div style="max-width: 500px; margin-left: auto; margin-right: auto; text-align: left; margin-right: 10px; margin-left: 10px;">
	<span style="font-size: 1.3em;">Selecione para vender:</span>
	<span style="float: right;"><%= link_to "Busca", sales_buscando_path %></span>	
</div>
<div  align="center" style="padding-bottom: 50px; width: 100%; min-width: 320px; margin-bottom: 40px">
	<% @goods.each do |good| %>
		<%= link_to new_sale_path(:param => good.id) do %>
			<div class="divStock"style="border: 1px solid #d9d9d9; max-width: 500px; min-width: 294px; height: 85px;margin-top: 1px; text-align: left;" >
				<div style="max-width: 400px; border: 1px solid transparent; height: 85px; white-space: nowrap;" >
					<div class="inlineblockDiv" style="width: 60px; height: 60px; float: left; border: 1px solid #d9d9d9; margin: 10px; margin-right: 5%">
					</div>

					<div class="inlineblockDiv" style="text-align: left; white-space: nowrap;">
						<div style="margin-top: 15px;">
							<b style="font-size: 1.2em;"> <%= good.description %></b>
							<br>
							<article style="margin-top: 2px;">
								<span style=" font-size: 0.85em; color: gray; margin-right: 15px;">Quantidade: <%= good.quantity %></span>
								<span style=" font-size: 0.85em; color: gray;">Data: <%= good.buy_day %>/<%= good.buy_month %> / <%= good.buy_year %></span>
							</article>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/sales/new.html.erb
<div style="max-width: 300px; background: #C0C0C0; border: 3px solid transparent; border-radius: 10px; margin: 5px; color: white;">
  <div style="text-align: left; margin-left: 10px;"><b> Vendendo: </b></div>
  <h3 style="margin-top:5px;"><%= @good.description %></h3>
</div>

<div class=" formDiv row">
  <%= form_for @sale, html: { autocomplete: "off" } do |f| %>
    <div style="text-align: left;">
      <%= f.label :quantity, "Quantidade:" %>
      <%= f.number_field :quantity, class: 'form-control' %>

      <%= f.label :sell_price, "Preço de venda por unidade: (R$)" %>
      <%= f.text_field :sell_price, step: 0.01, :placeholder =>'ex.: 123,45', class: 'form-control' %>

      <div style="width: auto;">
        <div class="inlineblockDiv">
          <%= f.label :sell_day , "Dia:" %>
          <%= f.text_field :sell_day, class: 'form-control', style: "width: 45px;" %>
        </div>

        <div class="inlineblockDiv">
          <%= f.label :sell_month, "Mês:" %>
          <%= f.text_field :sell_month, class: 'form-control', style: "width: 45px;" %>
        </div>

        <div class="inlineblockDiv">
          <%= f.label :sell_year, "Ano:" %>
          <%= f.text_field :sell_year, :placeholder => '2018', class: 'form-control', style: "width: 60px;" %>
        </div>
      </div>

      <%= f.label :sold_to, "Vendido a: (Opcional)" %>
      <%= f.text_field :sold_to, :placeholder => 'ex.: Comprador, Leilão, Empresa..', class: 'form-control' %>

  	  <%= f.hidden_field :good_id, :value => @good.id %>
    </div> 
    <br>
    <div class="actions">
      <%= f.submit "Cadastrar Venda", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<br>
<%= link_to "Voltar", :back %>

app/views/sales/searching.html.erb
<h5 align="center" style="color: gray;">Preencha apenas as informações que deseje filtrar </h5> 

<h2 align="center">Busca para venda</h2>
<div class="formDiv row">
	<%= form_tag "/sales/busca", autocomplete: 'off' do %>
		<div style="text-align: left;">
			<%= label :description, "Descrição ou Nome:" %>
			<%= text_field_tag :description, params[:description], class: 'form-control' %>

			<div style="width: auto;">
				<div class="inlineblockDiv" style="margin-left: auto;">
					<%= label :buy_day, "Dia:" %>
					<%= text_field_tag :buy_day, params[:buy_day], class: 'form-control', style: "width: 45px;" %>
				</div>
				<div class="inlineblockDiv" style="margin: auto;">
					<%= label :buy_month, "Mês:" %>
					<%= text_field_tag :buy_month, params[:buy_month], class: 'form-control', style: "width: 45px;" %>
				</div>
				<div class="inlineblockDiv" style="margin: auto;">
					<%= label :buy_year, "Ano:" %>
					<%= text_field_tag :buy_year, params[:buy_year], :placeholder => '2018', class: 'form-control', style: "width: 60px;" %>
				</div>
			</div>

			<%= label :kind, "Tipo de mercadoria:" %>
			<%= text_field_tag :kind, params[:kind], :placeholder => 'ex.: Cristal, Quadro, Cosmético..', class: 'form-control' %>
		</div>
		<br>
		<%= submit_tag "Buscar", class: "btn btn-primary buttons" %>
	<% end %>
</div>
<br>
<%= link_to "Voltar", :back %>