config/routes.rb
Rails.application.routes.draw do
  
  get    '/ajuda',   to: 'help#help'
  get    '/geral',   to: 'general#general'
  get    '/signup',  to: 'users#new'
  get    '/goods/buscando', to: 'goods#searching'
  get    '/sales/buscando', to: 'sales#searching'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, exception: [:new, :create]
  resources :goods
  resources :expenses
  resources :sales

  post  'sales/busca' => 'sales#search' 
  post  'goods/busca' => 'goods#search' 
  post 'geral/busca' => 'general#search'

  resources :users do
  	get :current, on: :collection # users#current
  end

  root 'users#current_user_menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
	<div class="headerDiv">
	<% if logged_in? %>
		<div class="header-hamburger">
			<span  onclick="openNav()">
  				<%= image_tag "menu_icon.png" %>
			</span>
		</div>
		<div class="header-logo">
			<b>Simple Merch</b>
		</div>	
		<%= link_to current_user do %>
			<div class="header-menu">
				<%= image_tag "home_icon.png" %>
			</div>
		<% end %>
	<% else %>
		<div align="center" style="margin-top: 10px; font-size: 1.6em; color: white;">
			<b>Simple Merch</b>
		</div>		
	<% end %>
</header>
<% if logged_in? %>
	<div id="Sidenav" class="sidenav">
		<span><%= link_to "Usuário", edit_user_path(current_user) %></span>
		<span><%= link_to "Contato" %>
	  <span style="border-top: 2px solid white; margin-top: 5px;"><%= link_to "Sair", logout_path, method: :delete %></span>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleMerch</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div align="center" class="main">
      <% if false %>
        <div class="flashDiv">
          <% flash.each do |message_type, message| %>
            <div style="text-align: center" class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>